version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: pg-knowledgebase
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: knowledgebase-backend
    ports:
      - "5010:5000"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    # environment:
      # DATABASE_URL: ${DATABASE_URL}
      # JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backend:/app
    command: yarn dev

volumes:
  pgdata:
